# Generated by Django 3.1.6 on 2021-02-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismspot',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
            preserve_default=False,
        ),
    ]
