# Generated by Django 3.1.6 on 2021-02-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tourismspot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourism_spot'),
        ),
    ]
