# Generated by Django 3.1.6 on 2021-02-09 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_attraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismspot',
            name='attractions',
            field=models.ManyToManyField(blank=True, default=[], to='api.Attraction'),
        ),
        migrations.AlterField(
            model_name='tourismspot',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
