# Generated by Django 3.1.6 on 2021-02-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210208_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
